//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayParking.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Parking
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string LicencePlate { get; set; }
        public bool IsFree { get; set; }
    }
    public class ParkingdbContext : DbContext
    {
        public DbSet<Parking> Parkings { get; set; }
    }
}
